---
published: true
layout: post
title:  파이썬 6-2장
date:   2025-01-17
categories: jekyll update
usemathjax: true
---

<head>
  <style>
    table.dataframe {
      white-space: normal;
      width: 100%;
      height: 240px;
      display: block;
      overflow: auto;
      font-family: Arial, sans-serif;
      font-size: 0.9rem;
      line-height: 20px;
      text-align: center;
      border: 0px !important;
    }

    table.dataframe th {
      text-align: center;
      font-weight: bold;
      padding: 8px;
    }

    table.dataframe td {
      text-align: center;
      padding: 8px;
    }

    table.dataframe tr:hover {
      background: #b8d1f3; 
    }

    .output_prompt {
      overflow: auto;
      font-size: 0.9rem;
      line-height: 1.45;
      border-radius: 0.3rem;
      -webkit-overflow-scrolling: touch;
      padding: 0.8rem;
      margin-top: 0;
      margin-bottom: 15px;
      font: 1rem Consolas, "Liberation Mono", Menlo, Courier, monospace;
      color: $code-text-color;
      border: solid 1px $border-color;
      border-radius: 0.3rem;
      word-break: normal;
      white-space: pre;
    }

  .dataframe tbody tr th:only-of-type {
      vertical-align: middle;
  }

  .dataframe tbody tr th {
      vertical-align: top;
  }

  .dataframe thead th {
      text-align: center !important;
      padding: 8px;
  }

  .page__content p {
      margin: 0 0 0px !important;
  }

  .page__content p > strong {
    font-size: 0.8rem !important;
  }

  </style>
</head>


# **나 혼자만 파이썬 레벨업 6-2화**



> **Lv.6**

>> **이경민**


### **예외 고급**

##### 예외 객체(exception object)

> try:<br>&#160;&#160;&#160;&#160;&#160;&#160;&#160;<u>예외가 발생할 가능성이 있는 구문</u><br>except 예외의 종류 as 예외 객체를 활용할 변수 이름:<br>&#160;&#160;&#160;&#160;&#160;&#160;&#160;<u>예외가 발생했을 때 실행할 구문</u>



```python
# try except 구문으로 예외 처리
try:
    number_input_a = int(input('정수 입력 >'))
    # 출력
    print('원의 반지름', number_input_a)
    print('원의 둘레', 2 * 3.14 * number_input_a)
    print('원의 넓이', 3.14 * number_input_a * number_input_a)
except Exception as exception:
    print('type(exception) :', type(exception))
    print('exception :', exception)
```

<pre>
type(exception) : <class 'ValueError'>
exception : invalid literal for int() with base 10: 'ㅋ'
</pre>
### **예외 구분하기**



##### 예외 객체를 사용하면 except 구문을 if 조건문처럼 사용해서 예외 구분 가능



```python
# 변수 선언
list_number = [52, 273, 32, 72, 100]

# try except 구문으로 예외 처리
try:
    # 숫자 입력
    number_input = int(input('정수 입력 >'))
    # 리스트의 요소 출력
    print('{}번째 요소 : {}'.format(number_input, list_number[number_input]))
except Exception as exception:
    # 예외 객체 출력
    print('type(exception)',type(exception))
    print('exception :', exception)
```

<pre>
type(exception) <class 'IndexError'>
exception : list index out of range
</pre>
### **예외 구분하기**



> try:<br>&#160;&#160;&#160;&#160;&#160;&#160;&#160;<u>예외가 발생할 가능성이 있는 구문</u><br>except 예외의 종류 A:<br>&#160;&#160;&#160;&#160;&#160;&#160;&#160;<u>예외 B가 발생했을 때 실행할 구문</u><br>except 예외의 종류 B:<br>&#160;&#160;&#160;&#160;&#160;&#160;&#160;<u>예외 B가 발생했을 때 실행할 구문</u><br>except 예외의 종류 C:<br>&#160;&#160;&#160;&#160;&#160;&#160;&#160;<u>예외 C가 발생했을 때 실행할 구문</u>



```python
# 변수 선언
list_number = [52, 273, 32, 72, 100]

# try except 구문으로 예외 처리
try:
    # 숫자 입력
    number_input = int(input('정수 입력 >'))
    # 리스트의 요소 출력
    print('{}번째 요소 : {}'.format(number_input, list_number[number_input]))
except ValueError:
    # ValueError가 발생하는 경우
    print('정수를 입력해주세요')
except IndexError:
    # IndexError가 발생
    print('리스트의 인덱스를 벗어났다')
```

<pre>
정수를 입력해주세요
</pre>
### **예외 구분 구문과 예외 객체**

##### **as 키워드**

##### 예외를 구분할 때 각각의 except 구문 뒤에 예외 객체를 붙여 활용



```python
# 변수 선언
list_number = [52, 273, 32, 72, 100]

# try except 구문으로 예외 처리
try:
    # 숫자 입력
    number_input = int(input('정수 입력 >'))
    # 리스트의 요소 출력
    print('{}번째 요소 : {}'.format(number_input, list_number[number_input]))
except ValueError as exception:
    # ValueError가 발생하는 경우
    print('정수를 입력해주세요')
    print('exception :', exception)
except IndexError as exception:
    # IndexError가 발생
    print('리스트의 인덱스를 벗어났다')
    print('exception :', exception)
```

<pre>
리스트의 인덱스를 벗어났다
exception : list index out of range
</pre>
### **모든 예외 잡기**


### 예외 처리는 했지만 예외를 못 잡는 경우



```python
# 변수 선언
list_number = [52, 273, 32, 72, 100]

# try except 구문으로 예외 처리
try:
    # 숫자 입력
    number_input = int(input('정수 입력 >'))
    # 리스트의 요소 출력
    print('{}번째 요소 : {}'.format(number_input, list_number[number_input]))
    예외.발생시켜주세요()   # 예외 발생
except ValueError as exception:
    # ValueError가 발생하는 경우
    print('정수를 입력해주세요')
    print('exception :', exception)
except IndexError as exception:
    # IndexError가 발생
    print('리스트의 인덱스를 벗어났다')
    print('exception :', exception)
```

<pre>
1번째 요소 : 273
</pre>
#### 예외라는 이름을 정의해놓지 않아 NameError가 뜬다



```python

# 변수 선언
list_number = [52, 273, 32, 72, 100]

# try except 구문으로 예외 처리
try:
    # 숫자 입력
    number_input = int(input('정수 입력 >'))
    # 리스트의 요소 출력
    print('{}번째 요소 : {}'.format(number_input, list_number[number_input]))
    예외.발생시키기()
except ValueError as exception:
    # ValueError가 발생하는 경우
    print('정수를 입력해주세요')
    print(type(exception), exception)
except IndexError as exception:
    # IndexError가 발생
    print('리스트의 인덱스를 벗어났다')
    print(type(exception), exception)
except Exception as exception:
    # 이외의 예외가 발생한 경우
    print('미리 파악하지 못한 예외가 발생했다')
    print(type(exception), exception)
```

<pre>
1번째 요소 : 273
미리 파악하지 못한 예외가 발생했다
<class 'NameError'> name '예외' is not defined
</pre>
### 아직 구현되지 않은 부분에서 강제로 예외 발생시키기



### **raise 구문**

- 아직 구현되지 않은 부분이므로 일부러 예외를 발생시켜 프로그램 죽게 해서 잊지 않게 하는 것

> raise 예외 객체



```python
# 입력
number = input('정수 입력 >')
number =int(num)
# 조건문 사용
if number > 0:
    # 양수일 때: 아직 미구현 상태
    raise NotImplemnetedError
else:
    # 음수일 때: 아직 미구현 상태
    raise NotImplemnetedError
```
